name: CI

# Use a concurrency group to avoid testing the same branch multiple times in parallel
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel the previous job

on:
  # Manual trigger
  workflow_dispatch:

  # When a commit is pushed to the master branch
  push:
    branches:
      - master

  # When a pull request is opened, synchronized, reopened
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        box:
          - ubuntu-desktop-24.04
          - ubuntu-desktop-26.04

    defaults:
      run:
        working-directory: ./boxes/${{ matrix.box }}

    steps:
      - name: Checkout the project
        uses: actions/checkout@v7

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: 1.15.3

      - name: Initialize Packer
        run: packer init .

      - name: Format the code
        run: packer fmt -check .

      - name: Validate the code
        run: packer validate .
