---
name: CI

"on":
  # Manual trigger
  workflow_dispatch:

  # When a commit is pushed
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        box:
          - ubuntu-desktop-24.04

    defaults:
      run:
        working-directory: ./boxes/${{ matrix.box }}

    steps:
      - name: Checkout the project
        uses: actions/checkout@v6

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: 1.15.3

      - name: Initialize Packer
        run: packer init .

      - name: Format the code
        run: packer fmt -check .

      - name: Validate the code
        run: packer validate .
